[package]
name = "protoc"
version = "2.0.4"
authors = ["Stepan Koltsov <stepan.koltsov@gmail.com>"]
license = "MIT/Apache-2.0"
homepage = "https://github.com/stepancheg/rust-protobuf/tree/master/protoc/"
repository = "https://github.com/stepancheg/rust-protobuf/tree/master/protoc/"
description = """
Protobuf protoc command as API
"""

[lib]
doctest = false
bench = false

[dependencies]
log = "0.*"
