[project]
name = "rust-protobuf-test"
version = "0.0.0"
authors = ["Stepan Koltsov <stepan.koltsov@gmail.com>"]

[lib]
doctest = false

[features]
default-features = []
proto3 = []
with-bytes = ["bytes", "protobuf/with-bytes"]

[build-dependencies]
protoc      = { path = "../protoc" }
protoc-rust = { path = "../protoc-rust" }
glob        = "0.2"
env_logger  = "0.*"

[dependencies.protobuf]
path = "../protobuf"

[dependencies.bytes]
version = "0.*"
optional = true
