# https://github.com/rust-lang-nursery/rustfmt/pull/1267
space_before_bound = true

array_layout = "Block"
normalize_comments = false
fn_args_layout = "Block"
fn_arg_indent = "Block"
fn_brace_style = "SameLineWhere"
fn_call_style = "Block"
fn_return_indent = "WithWhereClause"
reorder_imported_names = true
where_pred_indent = "Block"
closure_block_indent_threshold = -1
error_on_line_overflow = false
generics_indent = "Block"
reorder_imports_in_group = true
take_source_hints = true
use_try_shorthand = true
