sudo: false

language: rust

matrix:
  include:
  - rust: stable
    env: PROTOBUF_VERSION=3.1.0
  - rust: beta
    env: PROTOBUF_VERSION=3.1.0
  - rust: nightly
    env: PROTOBUF_VERSION=3.1.0
  - rust: stable
    env: PROTOBUF_VERSION=2.6.1
  - rust: stable
    env: PROTOBUF_VERSION=3.1.0 RUST_PROTOBUF_FEATURES=bytes
  - rust: nightly
    env: PROTOBUF_VERSION=3.1.0 RUST_PROTOBUF_FEATURES=bytes

before_install:
  - ./install-protobuf.sh
  - PATH=/home/travis/bin:$PATH protoc --version

script:
  - rustc --version
  # Full rebuild with regenerate
  - PATH=/home/travis/bin:$PATH src/full-rebuild.sh

notifications:
  email:
    on_success: never

# vim: set ts=2 sw=2 et:
