sudo: false

language: rust

matrix:
  include:
  - rust: stable
    env: PROTOBUF_VERSION=3.1.0
  - rust: beta
    env: PROTOBUF_VERSION=3.1.0
  - rust: nightly
    env: PROTOBUF_VERSION=3.1.0
  - rust: stable
    env: PROTOBUF_VERSION=2.6.1
  - rust: stable
    env: PROTOBUF_VERSION=3.1.0 RUST_PROTOBUF_FEATURES=with-bytes
  - rust: nightly
    env: PROTOBUF_VERSION=3.1.0 RUST_PROTOBUF_FEATURES=with-bytes

before_install:
  - ./install-protobuf.sh
  - PATH=/home/travis/bin:$PATH protoc --version

script:
  - rustc --version
  # Full rebuild with regenerate
  - PATH=/home/travis/bin:$PATH protobuf/full-rebuild.sh
  - PATH=/home/travis/bin:$PATH ./protoc/test.sh
  - PATH=/home/travis/bin:$PATH cargo build --all --features=with-bytes --bins --tests --examples
  # `cargo test --benches` and `#[feature(test)]` only works on nightly
  - test "$TRAVIS_RUST_VERSION" != "nightly" || PATH=/home/travis/bin:$PATH RUST_BACKTRACE=1 cargo test --all --benches

notifications:
  email:
    on_success: never

# vim: set ts=2 sw=2 et:
