[workspace]
members = [
    "protoc",
    "protoc/test-protoc",
    "protoc-rust",
    "protobuf",
    "protobuf-codegen",
    "protobuf-codegen-pure",
    "protobuf-codegen-pure-test",
    "protobuf-test",
    "protobuf-test-common",
    "perftest/vs-cxx",
    "perftest/bytes",
    "update-version",
]
