[workspace]
members = [
    "protoc",
    "protoc-bin-vendored",
    # Exclude test-protoc from the project, because it depends on binary
    #"protoc/test-protoc",
    "protoc-rust",
    "protobuf",
    "protobuf-fuzz",
    "protobuf-codegen",
    "protobuf-codegen-pure",
    "protobuf-codegen-pure-test",
    "protobuf-examples",
    "protobuf-test",
    "protobuf-test-common",
    "perftest/vs-cxx",
    "perftest/bytes",
]
