[package]
name = "protobuf-test-common"
version = "0.0.0"
authors = ["Stepan Koltsov <stepan.koltsov@gmail.com>"]
publish = false
description = """
Common code of protobuf tests
"""

[lib]
doctest = false
bench = false

[features]
default-features = []
proto3 = []
with-bytes = ["bytes", "protobuf/with-bytes"]

[dependencies]
glob         = "0.2"
log          = "0.*"
env_logger   = "0.5.*"
tempdir      = "~0.3"
serde        = "1.0"
serde_derive = "1.0"

[dependencies.protobuf]
path = "../protobuf"

[dependencies.protobuf-codegen]
path = "../protobuf-codegen"

[dependencies.bytes]
version = "0.*"
optional = true
