[project]
name = "protobuf-test-common"
version = "0.0.0"
authors = ["Stepan Koltsov <stepan.koltsov@gmail.com>"]
publish = false
description = """
Common code of protobuf tests
"""

[lib]
doctest = false

[features]
default-features = []
proto3 = []
with-bytes = ["bytes", "protobuf/with-bytes"]

[dependencies]
glob        = "0.2"
log         = "0.*"
env_logger  = "0.5.*"

[dependencies.protobuf]
path = "../protobuf"

[dependencies.bytes]
version = "0.*"
optional = true
