[package]

name = "protobuf"
version = "3.0.0-alpha.4"
authors = ["Stepan Koltsov <stepan.koltsov@gmail.com>"]
edition = "2018"
license = "MIT"
homepage = "https://github.com/stepancheg/rust-protobuf/"
repository = "https://github.com/stepancheg/rust-protobuf/"
documentation = "https://github.com/stepancheg/rust-protobuf/blob/master/README.md"
description = """
Rust implementation of Google protocol buffers
"""

[lib]
bench = false

[features]
with-bytes = ["bytes"]
with-serde = ["serde", "serde_derive"]
default = []

[dependencies]
bytes = { version = "1.0", optional = true }
thiserror = "1.0.30"
serde        = { version = "1.0", features = ["derive"], optional = true }
serde_derive = { version = "1.0", optional = true }

[package.metadata.docs.rs]
all-features = true
