[package]
name = "protobuf-codegen-pure"
version = "3.0.0"
authors = ["Stepan Koltsov <stepan.koltsov@gmail.com>"]
license = "MIT/Apache-2.0"
homepage = "https://github.com/stepancheg/rust-protobuf/tree/master/protobuf-codegen-pure/"
repository = "https://github.com/stepancheg/rust-protobuf/tree/master/protobuf-codegen-pure/"
description = """
Pure-rust codegen for protobuf using protobuf-parser crate

WIP
"""

[lib]
doctest = false

[dependencies]
protobuf = { path = "../protobuf", version = "=3.0.0" }
protobuf-codegen = { path = "../protobuf-codegen", version = "=3.0.0" }

[[bin]]

name = "parse-and-typecheck"
path = "src/bin/parse-and-typecheck.rs"
test = false
