[package]
name = "protobuf-examples-dynamic"
version = "0.0.0"
authors = ["Stepan Koltsov <stepan.koltsov@gmail.com>"]
edition = "2018"
publish = false

[dependencies]
protobuf = { path = "../../protobuf" }
protobuf-parse = { path = "../../protobuf-parse" }
tempfile = "3"
