[package]
name = "protoc-rust"
version = "3.0.0"
authors = ["Stepan Koltsov <stepan.koltsov@gmail.com>"]
license = "MIT/Apache-2.0"
homepage = "https://github.com/stepancheg/rust-protobuf/tree/master/protoc-rust/"
repository = "https://github.com/stepancheg/rust-protobuf/tree/master/protoc-rust/"
description = """
protoc --rust_out=... available as API. protoc needs to be in $PATH, protoc-gen-run does not.
"""

[lib]
doctest = false
bench = false

[dependencies]
protoc = { path = "../protoc", version = "=3.0.0" }
protobuf = { path = "../protobuf", version = "=3.0.0" }
protobuf-codegen = { path = "../protobuf-codegen", version = "=3.0.0" }
tempdir = "0.3"
