[package]
name = "protoc-rust"
version = "1.4.3"
authors = ["Stepan Koltsov <stepan.koltsov@gmail.com>"]
license = "MIT/Apache-2.0"
homepage = "https://github.com/stepancheg/rust-protobuf/protoc-rust/"
repository = "https://github.com/stepancheg/rust-protobuf/protoc-rust/"
description = """
protoc --rust_out=... available as API. protoc needs to be in $PATH, protoc-gen-run does not.
"""

[lib]
doctest = false

[dependencies]
protoc   = { path = "../protoc", version = "1.4.3" }
protobuf = { path = "../protobuf", version = "1.4.3" }
tempdir  = "0.3"
